### PR TITLE
Add support for API resource on laravel 5.5 and above

### PR DESCRIPTION
**Pull request by lj3lj3**
Add support for API resource on laravel 5.5 and above, which is useful when creating the model-based data structure.

### CODE REVIEW

**Comment by kbaryshnikov** [comment]
Thanks for your PR!

Please avoid unrelated changes (like newline in EOF).

Could you please also add/update a unit test? ServerTest seems like a good place.

**Comment by lj3lj3** [comment]
Thank you for your response here!
Right now, I need some help here, I'm stuck with resolving the `\Illuminate\Http\Request` in the unit test, I can't find a way to `bind` it, any advice would be appreciated!

**Comment by kbaryshnikov** [comment]
Why do you need to do that?
What's the case you're trying to cover?

**Comment by kbaryshnikov** [comment]
Implemented in v0.3.3 (see 7de2d2a)

**Pull request closed without merging**
